defaults: &defaults
  api_token: c4j6LvdTD42G699j7no2bxFArsavd3DB
  services:
    notification: ']92D8fW497.F64K{M+x9oP9J'
    renotification: u8rd&d4Y3N429zW3$Q(=X8bK

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  api_token: bs4o33YRwzdWJHs9kMT8RYvL9P4J7oXi
  services:
    notification: PNn96a9792B}}(2(EhKR46w2
    renotification: 2bifhg76^QYL4%6g86;=ML2A
