# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f18f2491b21e82eb7cdcb977db5a70a1db698511c39075f362e22d63cc6437d2a810b09218e4085c6b613a9a4d076c2c1c653d3b3e4628df9a97fc288de05007

test:
  secret_key_base: 67a3192b588875985442f439ed2267165492b33f7d8b2c0e0a7c28f742193cec1147dbb9ad39ec57378e19573aad898ac18cc8899a606c96b0e824eab47725af

# Do not keep production secrets in the repository,
# instead read values from the environment.

staging:
  secret_key_base: <%= Figaro.env.secret_key_base %>

production:
  secret_key_base: <%= Figaro.env.secret_key_base %>
