defaults: &defaults
  app_name: Zazo Notification
  version: 0.1.0
  authentication_method: digest
  stub_mobile_number: false
  rspec:
    profile_examples: 10

development:
  <<: *defaults
  authentication_method: basic
  stub_mobile_number: true

test:
  <<: *defaults

production:
  <<: *defaults
