defaults: &defaults
  app_name: Zazo Notification
  version: 0.1.0
  authentication_method: digest

development:
  <<: *defaults
  authentication_method: basic

test:
  <<: *defaults

production:
  <<: *defaults
